### PR TITLE
Bug 1832629: Add metrics for 1xx, 3xx, and 4xx request counters, add latency, track reused connections

### LINKED ISSUE #81: Router metrics don't expose 4xx
Is there a reason the router metrics don't expose any 4xx? 
We actually need those 4xx metrics for debugging and alerting.

### PR DESCRIPTION
**Pull request by smarterclayton**
A number of new metrics have been added to HAProxy that enable better insight into workloads.

The 1xx, 3xx, and 4xx counters will allow total request count to be assessed for non passthrough routes.

The queue and connect latency metrics will give visibility into moving window latency around overload and TLS termination latencies.

The reused connections metric will allow a rough breakdown of which services are experiencing connection churn.

The connections total metric is new and is more accurate than sessions, so use that for frontends.

Builds on top of #127

Fixes #81

### CODE REVIEW

File: pkg/router/metrics/haproxy/haproxy.go [hunk 1]
```diff
@@ -222,7 +227,7 @@ func NewExporter(opts PrometheusOptions) (*Exporter, error) {
 			43: newFrontendMetric("http_responses_total", "Total of HTTP responses.", prometheus.Labels{"code": "5xx"}),
 			44: newFrontendMetric("http_responses_total", "Total of HTTP responses.", prometheus.Labels{"code": "other"}),
 			48: newFrontendMetric("http_requests_total", "Total HTTP requests.", nil),
-			60: newFrontendMetric("http_average_response_latency_milliseconds", "Average response latency of the last 1024 requests in milliseconds.", nil),
```
Comment (jeremyeder) [inline pkg/router/metrics/haproxy/haproxy.go:225]: why?

Comment (smarterclayton) [reply pkg/router/metrics/haproxy/haproxy.go:225]: Frontends don't expose this metric.

Comment (smarterclayton) [reply pkg/router/metrics/haproxy/haproxy.go:225]: And never have.

**Comment by smarterclayton** [comment]
The router e2e failure is real, will investigate.

**Comment by smarterclayton** [comment]
Ready for review.
